CREATE DATABASE vet_clinic

CREATE TABLE animals (
	id int GENERATED BY DEFAULT AS IDENTITY,
	name varchar(50),
	date_of_birth date,
	escape_attempts int,
	neutered boolean,
	weight_kg decimal
);

ALTER TABLE animals
ADD species varchar(50);

CREATE TABLE owners (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	full_name VARCHAR(50),
	age int
);

CREATE TABLE species(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(50)
);

ALTER TABLE animals
DROP COLUMN species,
ADD COLUMN species_id integer,
ADD COLUMN owner_id integer,
ADD CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id) ON DELETE CASCADE,
ADD CONSTRAINT fk_owner FOREIGN KEY(owner_id) REFERENCES owners(id) ON DELETE CASCADE;