CREATE DATABASE vet_clinic

CREATE TABLE animals (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(50),
	date_of_birth date,
	escape_attempts int,
	neutered boolean,
	weight_kg decimal
);

ALTER TABLE animals
ADD species varchar(50);

CREATE TABLE owners (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	full_name VARCHAR(50),
	age int
);

CREATE TABLE species(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(50)
);

ALTER TABLE animals
DROP COLUMN species,
ADD COLUMN species_id integer,
ADD COLUMN owner_id integer,
ADD CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id) ON DELETE CASCADE,
ADD CONSTRAINT fk_owner FOREIGN KEY(owner_id) REFERENCES owners(id) ON DELETE CASCADE;

CREATE TABLE vets (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(50),
  age integer,
  date_of_graduation date
);

CREATE  TABLE specializations (
	species_id integer,
	vet_id integer,
	CONSTRAINT species_fk FOREIGN KEY (species_id) REFERENCES species(id) ON DELETE CASCADE,
	CONSTRAINT vet_fk FOREIGN KEY (vet_id) REFERENCES vets(id) ON DELETE CASCADE
);

CREATE TABLE visits (
	vet_id integer,
	animal_id integer,
 	visit_date date,
	CONSTRAINT vets_fk FOREIGN KEY (vet_id) REFERENCES vets(id) ON DELETE CASCADE,
	CONSTRAINT animals_fk FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE
);